create table if not exists users(
    user_id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(64),
    login varchar(30),
    name varchar(30),
    birthday date,
    status int
);

create table if not exists films(
    film_id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30),
    description varchar(200),
    release_date date,
    duration int,
    genre varchar(30)
);

create table if not exists film_liked(
    films_id long references films (film_id),
    users_id long references users (user_id)
);

create table if not exists user_friend(
    user_id long references users (user_id),
    friend_id long references users (user_id)
);

create table if not exists status (
    status_id long references users (user_id),
    name varchar
);

create table if not exists genre (
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30)
)